### 1) 회원가입
POST http://localhost:8080/api/signup
Content-Type: application/json

{
  "loginId": "test003",
  "password": "1234",
  "nickname": "test003"
}

### 2) 로그인
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "loginId": "test002",
  "password": "1234"
}

### 3) 로그인 사용자 정보 확인
GET http://localhost:8080/api/me

### 4) 설문 여부 확인
GET http://localhost:8080/api/auth/survey-check

### 5) 로그아웃
POST http://localhost:8080/api/auth/logout

### 6) 로그아웃 후 설문 여부 확인 - 세션 만료 테스트
GET http://localhost:8080/api/auth/survey-check

### 인프라 점수 산정 테스트
POST http://localhost:8080/api/infra/recommend
Content-Type: application/json

{
  "dongCodes": [1168010100, 1168010300, 1168010500]
}


### 인프라 점수 산정 테스트2
POST http://localhost:8080/api/infra/recommend
Content-Type: application/json

{
  "dongCodes": [1168010100,1168010300,1168010500,1168010600,1168010700,1168010800,1168011000,1168011100,1168011200,1168011300,1168011400,1168011500,1168011800,1168012000,1168012100,1168012200,1168012300,1168012400,1168012500,1168012600]
}

### 상세정보 테스트
### 2) 동 상세 요약 조회
GET http://localhost:8080/api/dashboard/dongs/1168010800?surveyId=4

### 3) 인프라 요소별 상세 조회 - 병원
GET http://localhost:8080/api/dashboard/dongs/1168010800/elements?surveyId=1&type=HOSPITAL

### 4) 인프라 요소별 상세 조회 - 지하철
GET http://localhost:8080/api/dashboard/dongs/1168010800/elements?surveyId=1&type=SUBWAY

### 5) 인프라 요소별 상세 조회 - 도서관
GET http://localhost:8080/api/dashboard/dongs/1168010800/elements?surveyId=1&type=LIBRARY

### 6) 인프라 요소별 상세 조회 - 대규모점포
GET http://localhost:8080/api/dashboard/dongs/1168010800/elements?surveyId=1&type=LARGE_STORE

