spring:
  servlet:
    session:
      timout: 30m
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}  # 개발: update / 운영: validate 또는 none
    show-sql: false # 운영환경에서는 false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

kakao:
  rest-api-key: ${KAKAO_REST_API_KEY}

odsay:
  rest-api-keys: ${ODSAY_REST_API_KEY_LIST}

frontserver:
  url: ${FRONT_SERVER_URL}